# Generated by Django 2.2.3 on 2019-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='num_dependencies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attribute',
            name='num_dependents',
            field=models.IntegerField(default=0),
        ),
    ]
